### ISSUE TITLE
Pump Settings synchronization fails if no data on diasend

### ISSUE THREAD

**Issue by jay-beco** [burnedikt/diasend-nightscout-bridge#24]
When Setting up NIGHTSCOUT_PROFILE_NAME the following message pops up:

yarn run v1.22.19
$ yarn build && node dist/run.js
$ tsc
Fetching diasend patient records between 2023-01-01T09:39:57.648Z and 2023-01-01T09:44:57.650Z
Fetching diasend patient records between 2023-01-01T09:39:57.648Z and 2023-01-01T09:44:57.648Z
Number of glucose records since 5 minutes ago (2023-01-01T09:39:57.648Z - 2023-01-01T09:44:57.650Z):  1
Sending 1 entries to nightscout
Sending 0 treatments to nightscout
Scheduling 0 records for processing in next run
Next run (Treatments) will be in in 5 minutes...
Next run (Entries) will be in in 5 minutes...

> TypeError: Cannot read properties of undefined (reading 'toLowerCase')
>     at /Users/janbeco/Documents/GitHub/diasend-nightscout-bridge/dist/diasend.js:158:65
>     at Generator.next (<anonymous>)
>     at fulfilled (/Users/janbeco/Documents/GitHub/diasend-nightscout-bridge/dist/diasend.js:5:58)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Next run (Pump Settings) will be in in 12 hours...

What is wrong?

**Comment by muthijammy** [comment]
- Same warning noticed in logs of Railway nightscout diasend-nightscout-bridge plugin but it is working good.

Production environment detected, enabling Minify
WARNING: express-minify cache directory is not writeable, fallback to memory cache.
Listening on port 6282 railway
Number of glucose records since an hour ago (2023-01-02T00:48:11.007Z - 2023-01-02T01:48:11.008Z):  0
Sending 0 entries to nightscout
Next run (Entries) will be in in 2 minutes...
Sending 0 treatments to nightscout
Updating basal profile based on 0 records
got data-received event, requesting reload
(node:1) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Scheduling 0 records for processing in next run
Next run (Treatments) will be in in 2 minutes...
TypeError: Cannot read property 'toLowerCase' of undefined
at /opt/app/node_modules/diasend-nightscout-bridge/dist/diasend.js:157:65
at Generator.next (<anonymous>)
at fulfilled (/opt/app/node_modules/diasend-nightscout-bridge/dist/diasend.js:5:58)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
Next run (Pump Settings) will be in in 12 hours...
Load Complete:
sgvs:3, profiles:1
data loaded: reloading sandbox data and updating plugins
Prefs: { warn: 30, urgent: 60, enableAlerts: undefined }
WS: emitted clear_alarm to all clients

**Comment by burnedikt** [comment]
I thnk this error was fixed already with version 1.1.1 of the library and[ this commit](https://github.com/burnedikt/diasend-nightscout-bridge/commit/aca4e23e7828789bf32973b720d5928ca2695828).

However, my nightscout fork isn't yet updated to use version 1.1.1, it's still [running on 1.0.0](https://github.com/burnedikt/cgm-remote-monitor/blob/38d7932212b7019d1941aedd2cc9cd741657c017/package.json#L89).
If you want to update to a newer version, you can manually update the version in `package.json` of your nightscout fork and run `npm install`, then commit the changes and push them back to github.

The error itself only happens on freshly started nightscout instances to the best of my knowledge, namely if no nightscout profile exists yet. It shouldn't happen if you started changing some settings within the nightscout profile editor or on subsequent runs, but I might be mistaken.

**Comment by burnedikt** [comment]
My bad, this seems to be unrelated to what I said and instead relates to the fact that the bridge tries to synchronize the lower and upper blood glucose target values from diasend. It seems like it cannot find the value within the pump settings at this url: `https://international.diasend.com/reports/<diasend-user-id>/insulin/pump-settings` (`<diasend-user-id` will be different for each user): 

![image](https://user-images.githubusercontent.com/6168665/210278123-391bc0d8-85d6-438b-8833-4bf06930916c.png)

To debug this, would be interesting what the both of you see within their diasend account's pump settings. You can find the settings by loging into diasend, setting the lanugage to english at login and then navigating to "Insulin" -> "Pump Settings".

**Comment by jay-beco** [comment]
Morning - strangely enough > ?! > Ypsopump

<img width="655" alt="Bildschirm­foto 2023-01-03 um 07 06 11" src="https://user-images.githubusercontent.com/36067186/210307192-fc404715-cb8c-49c9-b3ae-79d1e0f56ba8.png">

Not having any settings at all showing up explains at last part of the problem... ;)

**Comment by burnedikt** [comment]
At the very least, the bridge should probably handle this case more gracefully, but still weird that there are no pump settings in diasend.

**Comment by burnedikt** [comment]
One reason why there may be no pump settings available is because there are multiple pumps registered within diasend and the wrong one is set as active within the diasend patient profile, see also [this comment](https://github.com/burnedikt/diasend-nightscout-bridge/issues/23#issuecomment-1371506225). Can be configured at https://international.diasend.com/patient/profile.

**Comment by burnedikt** [comment]
Anyhow, the error should no longer appear with [Version 1.1.5](https://github.com/burnedikt/diasend-nightscout-bridge/pull/33#issuecomment-1371580658)

**Comment by jay-beco** [comment]
> 
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/36067186/210797613-dfce58ee-49ab-483b-b134-6d4f15f18868.png">
Just one pump and no additional configs and still no Info in the pump settings?! 

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/36067186/210798336-5d5e4ff8-ecfe-4e71-915a-8cf1b7ee0c4e.png">

But that's an issue on my side i guess. Does it have any implications with how the bridge works or what data will be shown in Nightscout or can I just leave it as it is? ..

**Comment by burnedikt** [comment]
> But that's an issue on my side i guess. Does it have any implications with how the bridge works or what data will be shown in Nightscout or can I just leave it as it is? ..

It will prevent the basal rate programmed into the pump from being shown. It'll also not import the Insulin:Carb-ratios and insulin sensitivity profiles. But those anyhow only make sense if you use nightscout's bolus calculator or other nightscout features. If you're just using nightscout for monitoring, I think it shouldn't be an issue. Still weird that the basal rate programmed into the pump does not show anywhere on diasend 😕
