### ISSUE TITLE
Switch to Glooko

### ISSUE THREAD

**Issue by fabkai** [burnedikt/diasend-nightscout-bridge#49]
Via mylife CamAPS it is now possible to have the data sent to Glooko instead of diasend (by June 14, 2023 the diasend account must have been migrated to Glooko). @burnedikt Are you planning to migrate the diasend-nightscout-bridge to Glooko as well?

**Comment by burnedikt** [comment]
Haven't looked into glooko yet but will definitely check it out in the next 2 months 😉 (not like there's a choice anyways). My personal hope would be that glooko is on fact "good enough" so nightscout is not needed on the first place, but not sure if my hopes are realistic. 

Have you already migrated to glooko?

**Comment by fabkai** [comment]
I have also not yet migrated to gkooko. 
But I think it would be great to have the values (insulin units and carbohydrates, etc.) still from glooko in Nightscout so that you can see them directly on your smartphone or smartwatch without having to actively use glooko. I would want to use glooko, like diasend rather for statistics and the diabetologist.
Therefore I would be very happy if you find the time and desire to change your bridge to glooko ;-)

**Comment by jay-beco** [comment]
I'm uncertain at the moment, but it appears that after my wife transferred the account, the bridge has been unable to retrieve data from Diasend. For example, I can no longer see the basal rate in Nightscout. Ever since the update, data collection from Diasend seems to have stopped. Could someone please verify and confirm this issue?

**Comment by burnedikt** [comment]
I would expect it to be a "one-way-road", i.e. once transfer happens to glooko, no data will be sent to diasend anymore and there's no way back. And latest on 14th of June, this project will cease to work, I'm afraid. 

As for glooko, it seems to be a fair bit more open towards 3rd party projects (like a potential glooko-to-nightscout-bridge) since there's even a [portal for APIs to access data on glooko](https://developers.glooko.com/). 

There also seems to be an implementation of a bridge for glooko to nightscout already: https://github.com/jpollock/glooko2nightscout-bridge. Has anyone tried it yet?

**Comment by burnedikt** [comment]
Sorry for accidentally locking this 😇 Still interested in getting feedback from anyone having tried glooko already.

**Comment by widmann** [comment]
As the migration will be enforced soon anyway and I got an extra free hour I dared to migrate my data (CamAPS FX + Dana-i) from Diasend to Glooko. TL;DR: In my opinion this appears to be a step backwards rather than forwards, unfortunately.

Glooko web-interface:
* Slightly more powerful than Diasend but considerably less accessible.
* Glucose axis always is 0-24 mmol/l. I did not find a way to adjust. Smaller details in the target range get lost.
* Temporary basal rates only visible in two specific views: Graphs - Overview - 1 day and Graphs - Calendar (too small to be useful).
* "Logbook" unreadable for me. Not designed for loop with constantly changing basal rates, apparently.
* "Insights" did not provide any insights. Not sure what this is intended for.
* Upload frequency 45 min here. No major improvement over Diasend but apparently at least predictable.
* Transfer of data from Diasend took about 24 hours to complete. Only then latest data became available.
* Plus: CSV format exported data will be easier to handle than Diasend Excel file, presumably.
* On the start page a "Potential Device Time Issue" error is reported. This might be specific to my CamAPS + pump combo (but the frequent mentions of the insulin amount bug in the app reviews might suggest that it is more common). The timestamps and summaries in the web interface graphs appear to be all correct at first glance. In the CVS export in the insulin_data.csv there are two Total Bolus/Total Insulin/Total Basal entries per day at 0:00 and 23:00.

App (Android):
* I could find no display of temporary basal rates anywhere. Major disappointment.
* Could not find a reliable way how to update the graph of the current day. Sometimes it was considerably behind the data available in the web interface. Update appears erratic and unrelated to any UI input. Major disappointment.
* Reported amount of insulin is doubled for past days. This problem only affects the app (iOS and Android!), web version is correct. This might be a CamAPS and/or timezone issue (see above) but looking at the app reviews the problem appears to be widespread and known to Glooko. Considering the manufacturer replies to the reviews I do not assume that reporting to customer support will actually help.
* Also no adjustment of glucose scales.
* Trends show min/max (?) error bars instead of the much more common (and informative, imho) percentiles.
* Could not find out how to interpret the carb counts on start page.
* Navigation is completely unintuitive (for me).
* Plus: Ability to add notes, training, medication, etc. In my opinion, this is the only relevant improvement over Diasend.
* iOS app is visually slightly more appealing but accessibility is even worse (for me).

Summary: A Glooko2Nightscout-Bridge would be highly appreciated :) (I did not yet try https://github.com/jpollock/glooko2nightscout-bridge).

**Comment by burnedikt** [comment]
After putting in some thought, I will not pursue a bridge from glooko to nightscout because I personally have little incentive to do so. The main reason here is the fact that the data in glooko has too much delay (~1 hour) to fulfill my near-real-time monitoring needs". And I (personally) don't need the data in nightscout for reporting purposes. I'm fine with glooko for that purpose.

I still encourage everyone who has the need to synchronize data from glooko to nightscout to take a look at https://github.com/jpollock/glooko2nightscout-bridge or contribute there. 

As for the other options available to have a monitoring solution, [xDrip in companion mode][xDrip-companion] (not to be confused with CamAPS Companion mode works great if all you need are the (realtime) CGM values. It does not synchronize any treatments data (bolus, temp basal, ...), though.

Alternatively, and particularly if you're anyways running on Android, [CamAPS Companion mode](https://www.youtube.com/watch?v=0ad_OVjxxrI) may be just the right tool for you. 

[xDrip-companion]: https://xdrip.readthedocs.io/en/latest/install/companion/
